name: Deploy Apps

on:
  push:
    branches:
      - main
    paths:
      - "manifest.json"
  pull_request:
    branches:
      - main
    paths:
      - "manifest.json"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Deploy App
        id: Deploy_Application
        env:
          ZELTHY_AUTH: ${{ secrets.ZELTHY_AUTH }}
          ZELTHY_GITHUB_AUTH: ${{ secrets.ZELTHY_GITHUB_AUTH }}
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
        run: |
          set -e  # Exit on error

          BRANCH_NAME="${GITHUB_REF_NAME}"

          case "$BRANCH_NAME" in
            "main") url=$(jq -r '.urls.prod' manifest.json) ;;
            "development") url=$(jq -r '.urls.dev' manifest.json) ;;
            "staging") url=$(jq -r '.urls.staging' manifest.json) ;;
            *) echo "Branch not recognized: $BRANCH_NAME"; exit 1 ;;
          esac

          if [[ -z "$url" || "$url" == "null" ]]; then
            echo "Error: URL not found in manifest.json"
            exit 1
          fi

          latest_version=$(jq -r '.app_versions | select(length > 0) | .[-1].version // empty' manifest.json)
          remark=$(jq -r '.app_versions | select(length > 0) | .[-1].remark // empty' manifest.json)

          if [[ -z "$latest_version" || "$latest_version" == "null" ]]; then
            echo "Error: latest_version not found in manifest.json"
            exit 1
          fi

          echo "URL: $url"
          echo "Latest Version: $latest_version"
          echo "Remark: $remark"

          echo "$url" "$BRANCH_NAME" "$remark" "$TEST_SECRET"

          chmod +x release.bash
          bash release.bash "$url" "$ZELTHY_AUTH" "$ZELTHY_GITHUB_AUTH" "$BRANCH_NAME" "$remark"
